#!/bin/bash

clear
REPO=$(dirname $PWD)
export PATH=$HOME/esp/xtensa-esp32-elf/bin:$PATH
#export IDF_PATH=$REPO/Tools/esp-idf
export IDF_PATH=/Users/eugene/Desktop/github/RetroESP32/Public/Software/Tools/esp-idf
