#!/bin/bash

SRC_PATH=`pwd`
REPO=$(dirname $PWD)
MKFW_PATH="$REPO/Odroid/odroid-go-firmware/tools/mkimg"
BUILD_PATH="../Build"
NAME="Retro-Odroid-Go.img"

#---------------------------------
# Styles
#---------------------------------
source helpers/styles

#---------------------------------
# Paths
#---------------------------------
source helpers/paths


clear
echo "--------------------------------------------------------------------------"
echo -e "${disk} ${green}Creating ${cyan}${NAME}${nc} Image"
echo "--------------------------------------------------------------------------"

$MKFW_PATH/mkimg "${NAME}" \
0xd000 $BUILD_PATH/Bins/ota_data_initial.bin \
0x1000 $BUILD_PATH/Bins/bootloader.bin \
0xf000 $BUILD_PATH/Bins/phy_init_data.bin \
0x8000 $BUILD_PATH/Bins/partitions.bin \
0x10000 $BUILD_PATH/Bins/Retro-Odroid-Go.bin

mv "${NAME}" "$BUILD_PATH/Image/${NAME}"

#---------------------------------
# Goodbye
#---------------------------------
cd $SRC_PATH
source helpers/goodbye
