#!/bin/bash

SRC_PATH=`pwd`
REPO=$(dirname $PWD)
MKFW_PATH="$REPO/Odroid/odroid-go-firmware/tools/mkimg"
BINS="../Firmware/build"
NAME="Retro-Odroid-Go.img"

#---------------------------------
# Styles
#---------------------------------
source helpers/styles

#---------------------------------
# Paths
#---------------------------------
source helpers/paths


clear
echo "--------------------------------------------------------------------------"
echo -e "${disk} ${green}Creating ${cyan}${NAME}${nc} Image"
echo "--------------------------------------------------------------------------"

$MKFW_PATH/mkimg "${NAME}" \
0xd000 $BINS/ota_data_initial.bin \
0x1000 $BINS/bootloader/bootloader.bin \
0xf000 $BINS/phy_init_data.bin \
0x10000 $BINS/Retro-Odroid-Go.bin \
0x8000 $BINS/partitions.bin

mv "${NAME}" "$REPO/Release/${NAME}"

#---------------------------------
# Goodbye
#---------------------------------
cd $SRC_PATH
source helpers/goodbye
